version: '3'


# Uses react-scripts dev server in a contianer
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api

    # bug in React-Scripts 3.4.1 (Mar 20, 2020)
    # fix is a hack
    # see https://github.com/facebook/create-react-app/issues/8688 for the bug
    stdin_open: true 

