version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build: ./app/api
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  nginx:
    build: ./app/webserver
    ports: 
      - 80:8080
    depends_on:
      - api

