version: '3'


# Uses react-scripts dev server instead of
#  building and serving with nginx
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api: 
  frontend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api

    # bug in React-Scripts 3.4.1 (Mar 20, 2020)
    # fix is a hack
    # see https://github.com/facebook/create-react-app/issues/8688 for the bug
    stdin_open: true 

