version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./app/api
    command: sh entrypoint.sh
    depends_on:
      - db

  nginx:
    build: ./app/webserver
    ports: 
      - 80:8080
    depends_on:
      - api

volumes:
  pgdata: