version: '3'


# Uses react-scripts dev server instead of
#  building and serving with nginx
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api: 
    build:
      context: ./app/api
      dockerfile: Dockerfile-dev
    command: sh entrypoint.sh
    depends_on:
      - db
      - redis
      - models
    ports:
      - 8000:8000
  redis:
    image: redis:5
    ports:
      - 6379:6379
  models:
    build:
      context: ./pytorch-implementation/ 
      dockerfile: Dockerfile-dev
